// Generate zod schemas + TS types from ../../../schemas/*.json (pydantic output).
// Run via `npm run generate` (wired into `make codegen`). Output is committed;
// CI fails on drift.
import { jsonSchemaToZod } from "json-schema-to-zod";
import { readdirSync, readFileSync, writeFileSync, mkdirSync, rmSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const schemasDir = resolve(here, "../../../../schemas");
const outDir = resolve(here, "../src/generated");

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

const header = "// GENERATED by libs/ts/jarvis-events/tools/generate-zod.mjs — do not edit.\n";
const names = [];

for (const file of readdirSync(schemasDir).sort()) {
  if (!file.endsWith(".json") || file === "subjects.json") continue;
  const name = file.replace(/\.json$/, "");
  const schema = JSON.parse(readFileSync(join(schemasDir, file), "utf8"));
  const zodCode = jsonSchemaToZod(schema, { name: `${name}Schema`, module: "esm", type: name });
  writeFileSync(join(outDir, `${name}.ts`), header + zodCode);
  names.push(name);
}

const subjects = JSON.parse(readFileSync(join(schemasDir, "subjects.json"), "utf8"));

const index = [
  header,
  ...names.map((n) => `export { ${n}Schema, type ${n} } from "./${n}.js";`),
  "",
  ...names.map((n) => `import { ${n}Schema as _${n} } from "./${n}.js";`),
  "",
  "/** NATS subject -> payload zod schema (mirror of jarvis_core.events.SUBJECTS). */",
  "export const SUBJECT_SCHEMAS = {",
  ...Object.entries(subjects).map(([subject, model]) => `  "${subject}": _${model},`),
  "} as const;",
  "",
  "export type Subject = keyof typeof SUBJECT_SCHEMAS;",
  "",
].join("\n");

writeFileSync(join(outDir, "index.ts"), index);
console.log(`generated ${names.length} schemas + index into src/generated/`);
