apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# No namespace transformer: rbac.yaml spans jarvis-system and jarvis.
resources:
- ../../base
images:
- name: ghcr.io/jonasgovaerts/jarvis/gateway
  newName: ghcr.io/jonasgovaerts/jarvis/gateway
  newTag: sha-6874bfd
