---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-webhook
  namespace: jarvis-system
spec:
  encryptedData:
    url: AgB58AR3CPB4rEc0Dj4eJGPT1zpIGxx2IXIL55rcKK5GaJe0lVDefeb8UbUzxJLViN8+urJznjVfUDuYJUaR8shEbp0uP4y3OoZRgtZAgZFPl3cp+IjIu2bdpRctN1jrSRo+eL14OqoxTjUwv2EDK5n2L+0bONy07WIwQaRhmeik/GIIn4q28gdm+/TPTX8DUy3Xfp81Yqc/zaXjSmBewCSuj91XkR738iVXbuDQyf5CCjo7Vp2CfUmngKJaYe/zJR6AJXOMHKdzrO/yP5LqqVxaM9EDeVLYSKO/X+CG40q9ec2jT7V31z/Peb988ADPm0+0W1lUtm1m49+bEqjKow1ljtHlnffd3sp1WxE2Tfln6kPRCRsQQy0L4YfS+6eCEH0O/FC1O+o/XgJ1LULIcnTrY1Nx62yIb103NgEciSj8B268oeiBwbL7vZib00ViBt6YNPXMEGvxWwMe32o+LiE6NGdfuYgfUyPFatSa+uQq/dqFR5lUnMK7Kul0zDBMCcqh40Cx5jOnJErGwOpw/6BSG6+EWvO8Nc7Zp01lx2vnZF0DT10In+TocT91y1N0KZXZaKv+10MPxZAympnQNXS55s+UPA1Rhy9BKLK68FJ7MSoP4wRN+UzlSVlBAkgEY6pKhtm2k3KmHXQQTo8Ulr7K0GU1mPepKE8j23n8JS2yE+NUf9XwWfL+PSLiTMMwCrN5H5cSioPU7kwtZanb4W2eF5lfYqqkh2EbkOjZdAujMiENqmINtezO0Z3qzQfQG+OUq+34+3tr7ujU0LQJkCv/4Yg2RA8bG7WtICMA8l9rfaws0yZCbvn/go+c9w7eLHTjnqshA1xVbEI1nDU1KXjiovMf4A3D/C3O
  template:
    metadata:
      name: discord-webhook
      namespace: jarvis-system
