apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jarvis-notifier
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/jonasgovaerts/jarvis
    targetRevision: main
    path: deploy/apps/notifier/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: jarvis-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
