apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-sealed-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: 2.17.x
    helm:
      valuesObject:
        # kubeseal's default lookup is sealed-secrets-controller in kube-system
        fullnameOverride: sealed-secrets-controller
        namespace: kube-system
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
