apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: ghcr.io/jonasgovaerts/jarvis/notifier
  newName: ghcr.io/jonasgovaerts/jarvis/notifier
  newTag: sha-24dcc9f
