apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- sealedsecret-gmail.yaml
images:
- name: ghcr.io/jonasgovaerts/jarvis/workspace
  newName: ghcr.io/jonasgovaerts/jarvis/workspace
  newTag: sha-5901e84
