---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gmail-credentials
  namespace: jarvis-system
spec:
  encryptedData:
    authorized_user.json: AgCZBWqUf2PLuVNHf740jdt7pLEtl3CZZWdVMF2tjThib8wjKrMVFBtFQoo1xKz2e8Y9Q18buy9YyJ3vp9ALMoIXWqhkZK7p52Ou56nihku3m6unh9WpHaF5c4pRAB4SlcA263wJrVCgV1irZjkFxRVBEgprx1NKa7w0Vtt9d59RgozVQjhXxooploqW79ZYC4iBqxgk9G5HeWmTQ9Uh41nCh0PjT8HBismfG9QJ2/fSEJaMcuEuE9blUHRj+QhFD0hSXkH49XwNn+3W9QuWP20S3b9VPAMGhigHhPtIV9HEY4XpB6p5grVLEVmCKjpYGnU7rJYvFjpn+OZm7XSubtLT6MjUUkbU2uV1BxoxL5AGUZYOp0QVWJ8MYr4HXZmn8Zaqq4W7jMq1LIJ8obN9gi5ojd4F3s8NkqZvC6biwBfvBbeso8Fbq2eFWMo1c6cy9MkA9kkFLRpTAAafQKswBwgRathAdxldCKFZMweLTMM6u7LpgJ8MWIZLVEATPssk6bk3qV2BuXu+SbuPbW9MiOFPREA82qLgJ2/PCK6wBzzcqFsbrqK2ux7MG36IHukRh4Uoxew4Mpo6NRLKUqwvCH/pXznUZh6mztsAWS98xOmhhEaa0fDDTRbjQwnsAGmRe9BJlpjeGCJOE5FcMv3gnzbWZx8sTpOC//7lvSUYsuIOhrmQ5OdgjX7GnylAIY/qsBIuxPZ4VO2CscuRZVXs0t5K7nMkhWhp19MNKaiKdsk0EbdqZsPU6JyUI+NAW03JhYPFiFFFXXUHH/pLHBo8jrWLjGMuReDBVaYAK+pmMxaBaDiOPXSxjAgYp0YqzFFaNhltLbX8pZn1RGsZtNQI1RYeC+WjUBCaCx5hwR012wAIWPCb4RabpmU4/DUwn3Pr6RFy+pJTqTdlhjjK/tgZDdpa1TLlcOIxMq30hpKhGblK/7nBPRiMgwJtoEq9HXhTT78gmZ/fWDGwjSce2mQ/CnulNywi92YAhSluLomVxV3ZxBbMZvYZ6OaCFF5LoN1FFTiEq9uCnP/epJF7I2k1JXma8bvkZ3gHp/dlKMEMIRexORC5+hsw/UPS0yYHUt1sI6ok4tw+cv4xs0lhvdQKCEC10sc=
  template:
    metadata:
      name: gmail-credentials
      namespace: jarvis-system
